### ISSUE TITLE
Certain stakeholders don't have a start budget

### ISSUE THREAD

**Issue by NickTUD** [eishub/tygron#31]
It seems that the TU Delft and the DUWO have a start budget, but that the stakeholder/4 percepts don't give a start budget for the other stakeholders.

[Image showing the percepts in debug mode](http://i.imgur.com/heuXQmI.png)

**Comment by klikooo** [comment]
I believe this can be changed in the tygron editor?

**Comment by NickTUD** [comment]
We just started a session as the Privaat Woningbouw and it showed that they had a starting budget, while you can see from my screenshot that it doesn't generate it in the percept. I suggest that someone should take the task upon them to fix this issue

**Comment by MaxGroenenboom** [comment]
Privaat woning bouw actually has a budget of 0, as you can see in [http://puu.sh/oZcyz/ad366c814a.png](http://puu.sh/oZcyz/ad366c814a.png), the budget is not bound to the stakeholder but to Level 1. If every stakeholder would add their budget to the starting budget instead of additional budget in Level 1, this percept would work.

**Comment by NickTUD** [comment]
Fixed by @dionytadema
