### ISSUE TITLE
Add powermockito to the project.

### ISSUE THREAD

**Issue by MaxGroenenboom** [eishub/tygron#51]
Powermockito can be used to, a.o, mock static methods. The most important use of this would be the ability to mock `ServicesManager.fireServiceEvent`. If we are able to do this we can test specific components without relying on the server, thus increasing the stability and the speed of our tests.

**Comment by levilime** [comment]
@MaxGroenenboom  I think this is an interesting idea worth investigating and implementing. But I think it is important to keep in mind to not ommit too much integration testing between server and client, because the build should break if there is discrepancy between what the server sends and what the client expects.

Also to speed up CI testing the travis.yml can be changed to  ommit "-Dcobertura.skip" at mvn test and delete the last command: mvn cobertura:check. That way the testsuite is not run twice.

**Comment by MaxGroenenboom** [comment]
@levilime Not entirely true. The server should either not modify their api, or notify us about it. To still account for changes in the server, it would be better to have a single test class that tests the server connection, and to have all other classes mock their server connection.

**Comment by levilime** [comment]
I think there is nothing wrong with the point I made, also I think mocking their API responses like you suggest is cool, but you also need to test whether the server really gives these responses back. Which you say will be tested. So this is worthwhile if there are a lot of server response duplicates which can be tested once and then mocked (which there are). So I don't see how we can't both be right :smile:

**Comment by MaxGroenenboom** [comment]
I did say we are both right, I suggested separate tests for the server connection, and to have all other tests mock the server connection ;)
This way we see if a tests fails because of the server, or because of our own code.

**Comment by levilime** [comment]
:+1: We'll use powermockito too, otherwise the added action log feature is hard to cover. We look forward to seeing your changes in the test suite, and we'll adapt to use your powermockito configuration when the PR rolls in.

**Comment by MaxGroenenboom** [comment]
Powermockito has been added (In #68)
