### ISSUE TITLE
Custom Action

### ISSUE THREAD

**Issue by klikooo** [eishub/tygron#60]
It is currently not possible to add custom actions. We will develop custom actions by extending TygronEntity and more classes (this was the idea of Wouter, so we have less merge conflicts).

**Comment by spiderbiggen** [comment]
What is the progress on this issue?

**Comment by MaxGroenenboom** [comment]
It is now possible to add custom actions, you can check out the branch here: https://github.com/Denpeer/tygron/tree/getRelevantAreas
The branch was originally for a certain action though, and it is now badly in a WIP phase. Anyone knows if it is possible to make a pull request from a certain commit of a branch, instead of the latest commit of a branch?

**Comment by MaxGroenenboom** [comment]
When I try to make a pull request and set the compare to a commit, it automatically switches from "Open a Pull Request" to "Comparing changes"...

**Comment by spiderbiggen** [comment]
you're right didn't see that. you could revert your branch to the commit you want to merge and then make the pull request

**Comment by MaxGroenenboom** [comment]
I managed to pull a subset of commits into a new branch, check out the new PR: #65
